name: Elixir CI

on:
  push:
    branches: [ "primary" ]
  pull_request:
    branches: [ "primary" ]

permissions:
  contents: read

env:
  ELIXIR_VERSION: '1.14.3'
  OTP_VERSION: '25'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    env:
      ImageOS: ubuntu20

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.OTP_VERSION }}
    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v3
      env:
        cache-name: cache-elixir-deps
      with:
        path: deps
        key: mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: $mix-${{ env.cache-name }}-
    - name: Cache compiled build
      id: cache-build
      uses: actions/cache@v3
      env:
        cache-name: cache-compiled-build
      with:
        path: _build
        key: mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: mix-${{ env.cache-name }}-
    - name: Install dependencies
      run: mix deps.get
    - name: Compiles without warnings
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
    - name: Run mix format
      run: mix format --check-formatted
    - name: Run credo
      run: mix credo --strict